---
driver:
  name: docker
  use_sudo: false
  hostname: salt
  privileged: true
  username: root
  cap_add:
    - sys_admin
  disable_upstart: false
  use_internal_docker_network: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: bootstrap-salt.sh
  salt_bootstrap_options: -MPfq git %s
  install_after_init_environment: true
  log_level: info
  sudo: false
  require_chef: false
  formula: tests
  run_salt_call: false
  init_environment: |
    echo 'auto_accept: true' > /tmp/auto-accept-keys.conf
    mkdir -p /etc/salt/master.d
    mv /tmp/auto-accept-keys.conf /etc/salt/master.d/auto-accept-keys.conf
    sh -c 't=$(shuf -i 1-15 -n 1); echo Sleeping $t seconds; sleep $t'

platforms:
  - name: amazon-1
    driver_config:
      image: amazonlinux:1
      platform: rhel
      run_command: /sbin/init
      provision_command:
        - yum install -y upstart
  - name: amazon-2
    driver_config:
      image: amazonlinux:2
      platform: rhel
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - yum -y install procps-ng
  - name: arch
    driver_config:
      image: archlinux/base
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - pacman -Syu --noconfirm --needed systemd grep awk procps which
        - systemctl enable sshd
    provisioner:
      salt_bootstrap_options: -MPfq -D -y -x python2 git %s
  - name: centos-8
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: centos-6
    driver_config:
      run_command: /sbin/init
      provision_command:
        - yum install -y upstart
    provisioner:
      salt_bootstrap_options: -MPfq -y -x python2.7 git %s
  - name: debian-8
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - apt-get install -y dbus
  - name: debian-9
    driver_config:
      run_command: /lib/systemd/systemd
  - name: debian-10
    driver_config:
      run_command: /lib/systemd/systemd
  - name: fedora-30
    driver_config:
      image: fedora:30
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - dnf -y install procps-ng
  - name: fedora-31
    driver_config:
      image: fedora:31
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - dnf -y install procps-ng
  - name: fedora-32
    driver_config:
      image: fedora:32
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - dnf -y install procps-ng
  - name: opensuse-15
    driver_config:
      image: opensuse/leap:15.1
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - zypper --non-interactive install --auto-agree-with-licenses dbus-1
        - zypper --non-interactive install --auto-agree-with-licenses sudo openssh which curl
        - systemctl enable sshd.service
    provisioner:
      salt_bootstrap_options: -MPfq -y -x python2 git %s
  - name: ubuntu-18.04
    driver_config:
      run_command: /lib/systemd/systemd
  - name: ubuntu-16.04
    driver_config:
      run_command: /lib/systemd/systemd

suites:
  - name: py2-git-2018-3
    provisioner:
      salt_version: 2018.3
  - name: py2-git-2019-2
    provisioner:
      salt_version: 2019.2
  - name: py2-git-3000
    provisioner:
      salt_version: 3000
  - name: py2-git-master
    provisioner:
      salt_version: master
  - name: py2-stable-2018-3
    provisioner:
      salt_version: 2018.3
      salt_bootstrap_options: -MP stable %s
    excludes:
      - arch
      - opensuse-15
      - fedora-30
      - fedora-31
      - fedora-32
  - name: py2-stable-2019-2
    provisioner:
      salt_version: 2019.2
      salt_bootstrap_options: -MP stable %s
    excludes:
      - arch
      - opensuse-15
      - fedora-30
      - fedora-31
      - fedora-32
  - name: py2-stable-3000
    provisioner:
      salt_version: 3000
      salt_bootstrap_options: -MP stable %s
    excludes:
      - arch
      - opensuse-15
      - fedora-30
      - fedora-31
      - fedora-32

  - name: py3-git-2018-3
    provisioner:
      salt_version: 2018.3
      salt_bootstrap_options: -x python3 -MPfq git %s
    excludes:
      - amazon-1
      - centos-6
      - debian-8
      - amazon-2
  - name: py3-git-3000
    provisioner:
      salt_version: 3000
      salt_bootstrap_options: -x python3 -MPfq git %s
    excludes:
      - arch
      - amazon-1
      - centos-6
      - debian-8
  - name: py3-git-2019-2
    provisioner:
      salt_version: 2019.2
      salt_bootstrap_options: -x python3 -MPfq git %s
    excludes:
      - amazon-1
      - centos-6
      - debian-8
  - name: py3-stable-2018-3
    provisioner:
      salt_version: 2018.3
      salt_bootstrap_options: -x python3 -MP stable %s
    excludes:
      - amazon-1
      - centos-6
      - debian-8
      - opensuse-15
      - amazon-2
  - name: py3-stable-2019-2
    provisioner:
      salt_version: 2019.2
      salt_bootstrap_options: -x python3 -MP stable %s
    excludes:
      - amazon-1
      - centos-6
      - debian-8
      - opensuse-15
      - arch
  - name: py3-stable-3000
    provisioner:
      salt_version: 3000
      salt_bootstrap_options: -x python3 -MP stable %s
    excludes:
      - amazon-1
      - centos-6
      - debian-8
      - opensuse-15
      - arch
  - name: py3-git-master
    provisioner:
      salt_version: master
      salt_bootstrap_options: -x python3 -MPfq -D git %s
    excludes:
      - arch
      - amazon-1
      - centos-6
      - debian-8
      - fedora-32
      - opensuse-15

  - name: latest
    provisioner:
      salt_version: latest
      salt_bootstrap_options: -MP stable %s
    excludes:
      - arch

verifier:
  name: shell
  remote_exec: false
  command: pytest --cache-clear -v -s -ra --log-cli-level=info tests/integration/
