name: Release

on:
  push:
    tags:
      - '*'

jobs:
  checksums:
    name: Update Release Checksums on Develop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        if: github.repository == 'saltstack/salt-bootstrap'
        with:
          ref: stable

      - name: Get bootstrap-salt.sh sha256sum
        if: github.repository == 'saltstack/salt-bootstrap'
        run: |
          echo "SH=$(sha256sum bootstrap-salt.sh | awk '{ print $1 }')" >> $GITHUB_ENV
          echo "BS_VERSION=$(sh bootstrap-salt.sh -v | awk '{ print $4 }')" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        if: github.repository == 'saltstack/salt-bootstrap'
        with:
          ref: develop

      - name: Set up Python 3.7
        if: github.repository == 'saltstack/salt-bootstrap'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Update Latest Release on README
        if: github.repository == 'saltstack/salt-bootstrap'
        run: |
          python3 .github/workflows/scripts/update-release-shasum.py ${{ env.BS_VERSION }} ${{ env.SH }}

      - name: Create Pull Request Against Develop
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update README.rst with ${{ env.BS_VERSION }} release sha256sum
          delete-branch: true
