name: Test FreeBSD & OpenBSD
on:
  workflow_call:
    inputs:
      distro-slug:
        type: string
        required: true
        description: The Distribution Slug

      display-name:
        type: string
        required: true
        description: The Display Name For The Job

      runs-on:
        type: string
        required: true
        description: The GitHub MacOS Worker To Run Workflow On

      instances:
        type: string
        required: true
        description: The Instances To Test

      timeout:
        type: number
        required: false
        default: 20
        description: The timeout(in minutes) for the workflow

env:
  VAGRANT_HOME: '${{ github.workspace }}/.vagrant.d'
  KITCHEN_LOCAL_YAML: 'kitchen.bsd.yml'

jobs:
  Test:
    name: ${{ matrix.instance }}
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout }}
    strategy:
      fail-fast: false
      matrix:
        instance: ${{ fromJSON(inputs.instances) }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler-cache: true

      - name: Update Vagrant
        run: |
          brew update
          brew install vagrant

      - name: Setup Vagrant Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.kitchen
            ${{ github.workspace }}/.vagrant.d/
          key: "${{ runner.os }}|vagrant|${{ inputs.distro-slug }}|${{ hashFiles('Gemfile', '.github/workflows/test-bsd.yml', 'kitchen.bsd.yml') }}"

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python Dependencies
        run: |
          pip install -U pip
          pip install -r tests/requirements.txt

      - name: Create Test Instance
        run: |
          bundle exec kitchen create ${{ matrix.instance }}-${{ inputs.distro-slug }} || \
            (sleep 10 && bundle exec kitchen create ${{ matrix.instance }}-${{ inputs.distro-slug }})

      - name: Test Bootstrap
        run: |
          bundle exec kitchen verify ${{ matrix.instance }}-${{ inputs.distro-slug }}

      - name: Destroy Test Instance
        if: always()
        run: |
          bundle exec kitchen destroy ${{ matrix.instance }}-${{ inputs.distro-slug }}

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ matrix.instance }}-${{ inputs.distro-slug }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
